FROM node:lts-slim

WORKDIR /usr/api

ENV PORT 8080

# COPY ../package*.json ./
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# FIXME: node_modulesなどの不要ファイル対応
COPY ../api ./

RUN npm ci --only=production
RUN npm run build
CMD [ "npm", "start" ]